version: '3.8'
services:
  playground-web-frontend:
    image: playground-web-frontend:latest
    environment:
      PORT: 4202
    ports:
      - 4202:4202
  playground-web-backend:
    image: playground-web-backend:latest
    ports:
      - 8080:8080

  # PostgreSQL Database
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: personalapp_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    networks:
      - app-network

# Define the shared network
networks:
  app-network:
    driver: bridge
