services:
  frontend:
    build:
      context: ./Frontend/Money.Safe
      dockerfile: Frontend.Dockerfile
    image: playground-web-frontend:latest
    ports:
      - "4200:80" # Nginx is exposing on port 80 inside the container
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./Backend/MoneySafe
      dockerfile: Backend.Dockerfile
    image: playground-web-backend:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/personalapp_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network


  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: personalapp_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
